FROM python:3.9.21

# 设置工作目录
WORKDIR /app

# 先更新apt源并安装系统依赖
RUN apt-get update \
    && apt-get install -y ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# 升级pip并安装Python依赖
RUN pip install --upgrade pip setuptools \
    && pip install --no-cache-dir -r requirements.txt

# 复制项目文件
COPY . .

# 设置环境变量
ENV PYTHONPATH=/app

# 启动命令
CMD ["python", "app/main.py"]
